services:
  - type: web
    name: backend
    root: backend
    buildCommand: npm install
    startCommand: npm start

  - type: static_site
    name: frontend
    root: frontend
    buildCommand: npm run build
    publishPath: "./build"