services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

  - type: static_site
    name: frontend
    root: frontend
    nodeVersion: 18.18.2
    buildCommand: |
      npm install --unsafe-perm --legacy-peer-deps
      npm run build
    staticPublishPath: "./build"