services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

services:
  - type: static_site
    name: frontend
    root: frontend
    buildCommand: npm run build
    publishPath: "./build"
    nodeVersion: 18.18.2