services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: tienda-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    root: frontend
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: build
