services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

services:
  - type: web
    name: tienda-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: frontend/build