services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

  - type: static_site
    name: tiendita-frontend
    buildCommand: npm run build
    staticPublishPath: "./build"
    root: frontend