services:
  - type: web
    name: tiendita-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: PORT
        value: 10000

  - type: static_site
    name: frontend
    root: frontend
    buildCommand: |
      npm install --unsafe-perm
      npm run build
    publishPath: "./build"
    envVars:
      - key: CI
        value: "false"